const tourPackages = [
  {
    id: 'tour-2d1n',
    kategori: 'multiday',
    nama: { id: 'Paket Tour Lombok 2 Hari 1 Malam', en: 'Lombok Tour Package 2 Days 1 Night' },
    harga: 270000,
    durasi: { id: '2 Hari 1 Malam', en: '2 Days 1 Night' },
    gambar: 'tour-2d1n.jpg',
    detail: {
      id: 'Nikmati keindahan Lombok dalam paket tour 2 hari 1 malam. Kunjungi destinasi terbaik dengan nyaman.',
      en: 'Enjoy the beauty of Lombok in a 2 days 1 night tour package. Visit the best destinations comfortably.',
    },
    itinerary: [
      { title: { id: 'Bandara/Hotel → Wisata Senggigi → Pusuk → Kota Mataram', en: 'Airport/Hotel → Senggigi Tour → Pusuk → Mataram City' }, desc: { id: 'Penjemputan di bandara/hotel, dilanjutkan wisata Senggigi, kunjungan monyet di Pusuk, dan wisata kuliner Kota Mataram.', en: 'Pick up at airport/hotel, continue to Senggigi tour, monkey visit at Pusuk, and culinary tour of Mataram City.' } },
      { title: { id: 'Check Out → Taman Narmada → Bandara/Hotel', en: 'Check Out → Narmada Park → Airport/Hotel' }, desc: { id: 'Setelah check out, kunjungi Taman Narmada, lalu antar ke bandara/hotel.', en: 'After check out, visit Narmada Park, then drop off to airport/hotel.' } },
    ],
    include: ['Transport AC', 'Driver Guide', 'BBM', 'Parkir'],
    exclude: ['Tiket Masuk', 'Makan', 'Penginapan'],
  },
  {
    id: 'tour-3d2n',
    kategori: 'multiday',
    nama: { id: 'Paket Tour Lombok 3 Hari 2 Malam', en: 'Lombok Tour Package 3 Days 2 Nights' },
    harga: 400000,
    durasi: { id: '3 Hari 2 Malam', en: '3 Days 2 Nights' },
    gambar: 'tour-3d2n.jpg',
    detail: {
      id: 'Jelajahi Lombok lebih dalam dengan paket 3 hari 2 malam. Kunjungi pantai eksotis dan budaya lokal.',
      en: 'Explore Lombok deeper with a 3 days 2 nights package. Visit exotic beaches and local culture.',
    },
    itinerary: [
      { title: { id: 'Bandara/Hotel → Pantai Senggigi → Makam Loang Baloq', en: 'Airport/Hotel → Senggigi Beach → Loang Baloq Tomb' }, desc: { id: 'Penjemputan, kunjungan Pantai Senggigi dan Makam Loang Baloq.', en: 'Pick up, visit Senggigi Beach and Loang Baloq Tomb.' } },
      { title: { id: 'Wisata Kota Mataram → Taman Mayura → Narmada', en: 'Mataram City Tour → Mayura Park → Narmada' }, desc: { id: 'Tour Kota Mataram, Taman Mayura, dan Taman Narmada.', en: 'Mataram City tour, Mayura Park, and Narmada Park.' } },
      { title: { id: 'Check Out → Bandara/Hotel', en: 'Check Out → Airport/Hotel' }, desc: { id: 'Check out dan antar ke bandara/hotel.', en: 'Check out and drop off to airport/hotel.' } },
    ],
    include: ['Transport AC', 'Driver Guide', 'BBM', 'Parkir'],
    exclude: ['Tiket Masuk', 'Makan', 'Penginapan'],
  },
  {
    id: 'tour-4d3n',
    kategori: 'multiday',
    nama: { id: 'Paket Tour Lombok 4 Hari 3 Malam', en: 'Lombok Tour Package 4 Days 3 Nights' },
    harga: 600000,
    durasi: { id: '4 Hari 3 Malam', en: '4 Days 3 Nights' },
    gambar: 'tour-4d3n.jpg',
    detail: {
      id: 'Liburan lebih lama dengan paket 4 hari 3 malam. Kunjungi lebih banyak destinasi menarik.',
      en: 'Longer vacation with 4 days 3 nights package. Visit more attractive destinations.',
    },
    itinerary: [
      { title: { id: 'Bandara/Hotel → Senggigi', en: 'Airport/Hotel → Senggigi' }, desc: { id: 'Penjemputan, check in hotel, santai di Senggigi.', en: 'Pick up, check in hotel, relax at Senggigi.' } },
      { title: { id: 'Pantai Pink → Bukit Merese', en: 'Pink Beach → Merese Hill' }, desc: { id: 'Wisata Pantai Pink dan Bukit Merese di Mandalika.', en: 'Visit Pink Beach and Merese Hill in Mandalika.' } },
      { title: { id: 'Desa Sade → Pantai Kuta', en: 'Sade Village → Kuta Beach' }, desc: { id: 'Kunjungan Desa Adat Sade dan Pantai Kuta Lombok.', en: 'Visit Sade Traditional Village and Kuta Lombok Beach.' } },
      { title: { id: 'Check Out → Bandara/Hotel', en: 'Check Out → Airport/Hotel' }, desc: { id: 'Check out dan antar ke bandara/hotel.', en: 'Check out and drop off to airport/hotel.' } },
    ],
    include: ['Transport AC', 'Driver Guide', 'BBM', 'Parkir'],
    exclude: ['Tiket Masuk', 'Makan', 'Penginapan'],
  },
  {
    id: 'tour-5d4n',
    kategori: 'multiday',
    nama: { id: 'Paket Tour Lombok 5 Hari 4 Malam', en: 'Lombok Tour Package 5 Days 4 Nights' },
    harga: 750000,
    durasi: { id: '5 Hari 4 Malam', en: '5 Days 4 Nights' },
    gambar: 'tour-5d4n.jpg',
    detail: {
      id: 'Eksplorasi Lombok secara maksimal dengan paket 5 hari 4 malam. Liburan tak terlupakan!',
      en: 'Maximum exploration of Lombok with 5 days 4 nights package. Unforgettable vacation!',
    },
    itinerary: [
      { title: { id: 'Bandara/Hotel → Senggigi', en: 'Airport/Hotel → Senggigi' }, desc: { id: 'Penjemputan dan check in.', en: 'Pick up and check in.' } },
      { title: { id: 'Gili Trawangan', en: 'Gili Trawangan' }, desc: { id: 'Trip ke Gili Trawangan, snorkeling, dan sunset.', en: 'Trip to Gili Trawangan, snorkeling, and sunset.' } },
      { title: { id: 'Mandalika → Pantai Pink', en: 'Mandalika → Pink Beach' }, desc: { id: 'Wisata KEK Mandalika, Pantai Pink, dan Bukit Merese.', en: 'Tour to Mandalika SEZ, Pink Beach, and Merese Hill.' } },
      { title: { id: 'Desa Sade → Sukarara → Kota Mataram', en: 'Sade Village → Sukarara → Mataram City' }, desc: { id: 'Kunjungan desa tenun Sukarara dan desa adat Sade.', en: 'Visit Sukarara weaving village and Sade traditional village.' } },
      { title: { id: 'Check Out → Bandara/Hotel', en: 'Check Out → Airport/Hotel' }, desc: { id: 'Check out dan antar ke bandara/hotel.', en: 'Check out and drop off to airport/hotel.' } },
    ],
    include: ['Transport AC', 'Driver Guide', 'BBM', 'Parkir'],
    exclude: ['Tiket Masuk', 'Makan', 'Penginapan'],
  },
  {
    id: 'honeymoon-3d2n',
    kategori: 'honeymoon',
    nama: { id: 'Paket Honeymoon Lombok 3 Hari 2 Malam', en: 'Lombok Honeymoon Package 3 Days 2 Nights' },
    harga: 3000000,
    durasi: { id: '3 Hari 2 Malam', en: '3 Days 2 Nights' },
    gambar: 'honeymoon-3d2n.jpg',
    detail: {
      id: 'Liburan romantis bersama pasangan dengan paket honeymoon eksklusif di Lombok.',
      en: 'Romantic vacation with your partner with exclusive honeymoon package in Lombok.',
    },
    include: ['Transport AC', 'Hotel 2 Malam', 'BBM', 'Driver Guide'],
    exclude: ['Tiket Masuk', 'Makan', 'Airport tax'],
  },
  {
    id: 'honeymoon-4d3n',
    kategori: 'honeymoon',
    nama: { id: 'Paket Honeymoon Lombok 4 Hari 3 Malam', en: 'Lombok Honeymoon Package 4 Days 3 Nights' },
    harga: 3725000,
    durasi: { id: '4 Hari 3 Malam', en: '4 Days 3 Nights' },
    gambar: 'honeymoon-4d3n.jpg',
    detail: {
      id: 'Pengalaman honeymoon yang lebih panjang dengan kunjungan ke destinasi romantis Lombok.',
      en: 'Longer honeymoon experience with visits to romantic Lombok destinations.',
    },
    include: ['Transport AC', 'Hotel 3 Malam', 'BBM', 'Driver Guide'],
    exclude: ['Tiket Masuk', 'Makan', 'Airport tax'],
  },
  {
    id: 'trip-air-terjun',
    kategori: 'harian',
    nama: { id: 'Tour Harian - Trip Air Terjun', en: 'Daily Tour - Waterfall Trip' },
    harga: 260000,
    durasi: { id: '1 Hari', en: '1 Day' },
    gambar: 'waterfall.jpg',
    detail: {
      id: 'Nikmati keindahan air terjun di Lombok. Cocok untuk pecinta alam dan fotografi.',
      en: 'Enjoy the beauty of waterfalls in Lombok. Perfect for nature lovers and photography.',
    },
    include: ['Transport AC', 'Driver Guide', 'BBM'],
    exclude: ['Tiket Masuk', 'Makan'],
  },
  {
    id: 'trip-gili-nanggu',
    kategori: 'harian',
    nama: { id: 'Tour Harian - Trip Gili Nanggu', en: 'Daily Tour - Gili Nanggu Trip' },
    harga: 258000,
    durasi: { id: '1 Hari', en: '1 Day' },
    gambar: 'gili-nanggu.jpg',
    detail: {
      id: 'Liburan ke Gili Nanggu, surga tersembunyi di Lombok Barat. Snorkeling dan santai di pantai.',
      en: 'Trip to Gili Nanggu, a hidden paradise in West Lombok. Snorkeling and relaxing on the beach.',
    },
    include: ['Transport AC', 'Driver Guide', 'BBM', 'Boat'],
    exclude: ['Tiket Masuk', 'Makan', 'Snorkeling gear'],
  },
  {
    id: 'trip-gili-trawangan',
    kategori: 'harian',
    nama: { id: 'Tour Harian - Trip Gili Trawangan', en: 'Daily Tour - Gili Trawangan Trip' },
    harga: 385000,
    durasi: { id: '1 Hari', en: '1 Day' },
    gambar: 'gili-trawangan.jpg',
    detail: {
      id: 'Jelajahi Gili Trawangan, pulau paling populer di Lombok. Snorkeling, sunset, dan bersepeda.',
      en: 'Explore Gili Trawangan, the most popular island in Lombok. Snorkeling, sunset, and cycling.',
    },
    include: ['Transport AC', 'Driver Guide', 'BBM', 'Boat'],
    exclude: ['Tiket Masuk', 'Makan', 'Snorkeling gear'],
  },
  {
    id: 'trip-pantai-pink',
    kategori: 'harian',
    nama: { id: 'Tour Harian - Trip Pantai Pink', en: 'Daily Tour - Pink Beach Trip' },
    harga: 290000,
    durasi: { id: '1 Hari', en: '1 Day' },
    gambar: 'pink-beach.jpg',
    detail: {
      id: 'Kunjungi Pantai Pink yang eksotis dengan pasir berwarna merah muda yang unik.',
      en: 'Visit the exotic Pink Beach with its unique pink-colored sand.',
    },
    include: ['Transport AC', 'Driver Guide', 'BBM'],
    exclude: ['Tiket Masuk', 'Makan'],
  },
  {
    id: 'trip-mandalika',
    kategori: 'harian',
    nama: { id: 'Tour Harian - Trip Mandalika', en: 'Daily Tour - Mandalika Trip' },
    harga: 230000,
    durasi: { id: '1 Hari', en: '1 Day' },
    gambar: 'mandalika.jpg',
    detail: {
      id: 'Jelajahi KEK Mandalika, sirkuit MotoGP, Pantai Kuta, dan Bukit Merese.',
      en: 'Explore Mandalika SEZ, MotoGP circuit, Kuta Beach, and Merese Hill.',
    },
    include: ['Transport AC', 'Driver Guide', 'BBM'],
    exclude: ['Tiket Masuk', 'Makan'],
  },
  {
    id: 'trip-sembalun',
    kategori: 'harian',
    nama: { id: 'Tour Harian - Trip Wisata Sembalun', en: 'Daily Tour - Sembalun Trip' },
    harga: 225000,
    durasi: { id: '1 Hari', en: '1 Day' },
    gambar: 'sembalun.jpg',
    detail: {
      id: 'Nikmati udara sejuk dan pemandangan indah Sembalun, kaki Gunung Rinjani.',
      en: 'Enjoy the cool air and beautiful views of Sembalun, at the foot of Mount Rinjani.',
    },
    include: ['Transport AC', 'Driver Guide', 'BBM'],
    exclude: ['Tiket Masuk', 'Makan'],
  },
];

const getTourWA = (tour) => {
  const noHP = "6281999868882";
  const nama = tour.nama.id;
  const text = `Halo Azizan Travel Lombok, Saya Memesan ${nama}.`;
  return `https://wa.me/${noHP}?text=${encodeURIComponent(text)}`;
};
